[package]
name = "img-rust"
version = "0.1.0"
authors = ["tiffany1618 <tiffany9342@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rulinalg = "0.4.2"