[package]
name = "imgproc-rs"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "Image processing library for Rust"
authors = ["Tiffany Chieu <tiffany9342@gmail.com>"]
readme = "README.md"
repository = "https://github.com/tiffany1618/imgproc-rs"
homepage = "https://github.com/tiffany1618/imgproc-rs"
exclude = [
    "tests/*"
]
keywords = ["image", "image-processing"]
categories = ["multimedia::images"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
rulinalg = "0.4"